name: CI Pipeline

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push a la rama principal
  pull_request:
    branches:
      - main  # Ejecutar cuando se haga pull request a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usar un entorno Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clonar el repositorio

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Usar la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Instalar pytest para ejecutar pruebas

      - name: Run Python script
        run: python Hola.py  # Ejecutar el archivo Hola.py

      - name: Run tests
        run: python -m pytest test_Hola.py  # Ejecutar el archivo de pruebas test_Hola.py

      - name: Run performance tests
        run: |
          echo "Ejecutando pruebas de rendimiento..."  

      - name: Deploy to Production
        if: success()  # Solo si las pruebas anteriores pasan
        run: |
          echo "Desplegando a producción..."  
