name: CI Pipeline

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push a la rama principal
  pull_request:
    branches:
      - main  # Ejecutar cuando se haga pull request a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usar un entorno Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clonar el repositorio

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Usar la versión de Python que necesitas

      - name: Run Python script
        run: python hola.py  # Ejecutar el archivo hola.py
