name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Python script
        run: python Hola.py

      - name: Run tests
        run: python -m pytest test_Hola.py

      # Etapa de Monitoreo en Producción
      - name: Monitor Production Metrics
        run: |
          echo "Iniciando monitoreo de producción..."
          # Simulación de monitoreo (logs básicos)
          echo "Monitoreo: El sistema está en funcionamiento" >> production.log
          echo "Métrica: Tiempo de respuesta - 200ms" >> production.log
          echo "Métrica: Errores detectados - 0" >> production.log
